### ISSUE TITLE
Seguir links internos

### ISSUE THREAD

**Issue by nawarian** [PODEntender/estatista#11]
Atualmente o projeto não segue links internos. Isto nos impede de ter uma cobertura total do site navegável.
Um exemplo muito importante é o link `https://estatista.podentender.com/category/podcast`. A paginação ao fim do documento não funciona.

Em https://github.com/PODEntender/estatista/blob/master/src/static-generator.js#L38 há uma chamada para a extração de links do documento HTML. É necessário adicionar uma regra para `a[href]` cujo link seja interno para que possamos seguir aquele link também.

**Comment by JandersonConstantino** [comment]
Bom dia,
Achei interessante o que precisa ser desenvolvido.
Tem algum prazo em mente para conclusão?

**Comment by nawarian** [comment]
Bom dia @JandersonConstantino! Por enquanto não temos prazo. Os bugs nós queremos resolver o quanto antes pra poder levar a versão estática do site pro ar.

Esse aqui é aparentemente bem fácil pra começar :)

Me diz se tu tiver interesse. Do contrário eu vou corrigir até hoje de noitinha
