### ISSUE TITLE
Criar robots.txt

### ISSUE THREAD

**Issue by nawarian** [PODEntender/estatista#21]
- noindex todas páginas .html
- adicionar sitemap

Possível forma de implementar:

1. Adicionar um handler `afterBuild` (ver [bootstrap.php)](https://github.com/PODEntender/estatista/blob/master/bootstrap.php)
2. Implementar um application service + repository para propor as regras no `robots.txt`
3. Tornar as regras do `robots.txt` configuráveis

**Comment by Morkhusz** [comment]
Adicionado pull request #42 que pretende resolver esta issue
